package thaumcraft.common.tiles.crafting;

public class CrucibleDecayLogic {

    public static final int DECAY_START_DELAY = 400;
    public static final int DECAY_INTERVAL = 100;

    /**
     * Determines if aspect decay should be active.
     */
    public static boolean isDecayActive(long ticksWithoutCrafting) {
        return ticksWithoutCrafting > DECAY_START_DELAY;
    }

    /**
     * Determines if a decay event should occur on the current tick.
     */
    public static boolean shouldDecayThisTick(long ticksWithoutCrafting) {
        if (!isDecayActive(ticksWithoutCrafting)) {
            return false;
        }
        return (ticksWithoutCrafting - DECAY_START_DELAY) % DECAY_INTERVAL == 0;
    }

    /**
     * Calculates the amount of flux pollution generated by a single decayed aspect.
     */
    public static float getAuraFluxPollution() {
        return 0.25f;
    }

    /**
     * Determines if a decayed aspect should spill onto the floor as Flux Goo
     * rather than venting as gas into the aura.
     * @param randomValue A random value between 0.0 and 1.0.
     * @return true if it should spill as goo.
     */
    public static boolean shouldSpillAsGoo(float randomValue) {
        return randomValue < 0.25f;
    }
}
