package thaumcraft.common.items.consumables.logic;

/**
 * Pure, headless domain logic engine for Bottle of Taint.
 * Zero Minecraft server/registry dependencies.
 */
public class BottleTaintLogic {

    /**
     * Calculates the flux aura pollution generated by smashing/consuming bottles of taint.
     * Each bottle generates 5 units of flux aura pollution.
     *
     * @param bottleCount number of bottles consumed
     * @return flux pollution amount (non-negative)
     */
    public static int calculateFluxAuraPollution(int bottleCount) {
        return Math.max(0, bottleCount) * 5;
    }

    /**
     * Calculates the taint spread radius around the bottle consumption point.
     *
     * @param bottleCount number of bottles consumed
     * @return taint spread radius in blocks (non-negative)
     */
    public static float calculateTaintSpreadRadius(int bottleCount) {
        return Math.max(0.0f, bottleCount * 2.5f);
    }

    /**
     * Duration in ticks of the taint poison effect applied to nearby entities.
     *
     * @return duration in ticks (200 ticks = 10 seconds)
     */
    public static int getTaintPoisonDurationTicks() {
        return 200;
    }
}
